# Generated by Django 4.2.2 on 2023-07-12 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contactus',
            new_name='Contact',
        ),
        migrations.DeleteModel(
            name='Home',
        ),
    ]
